// src/views/GameView.vue
<script setup lang="ts">
import { provide } from 'vue'

import CorrectAnswer from '@/components/CorrectAnswer.vue'
import KeyCombinationForm from '@/components/KeyCombinationForm.vue'
import PieChart from '@/components/PieChart.vue'
import QuestionShow from '@/components/QuestionShow.vue'
import RestoreButton from '@/components/RestoreButton.vue'
import ShortcutsShow from '@/components/ShortcutsShow.vue'
import ToolsAndCategoriesModal from '@/components/ToolsAndCategoriesModal.vue'
import useEventListener from '@/composables/use-event-listener'
import useKeyboardEventListener from '@/composables/use-keyboard-event-listener'
import createGameStore from '@/stores/game'
import GameKey from '@/stores/game-key'
import {
  NavigatorExtend,
  NavigatorKeyboard,
  Shortcut,
} from '@/types/interfaces'
import Keyboard from '@/utils/keyboard'
import lockKeyboard from '@/utils/lock-keyboard'

const props = withDefaults(
  defineProps<{
    shortcuts?: Shortcut[] | undefined
  }>(),
  {
    shortcuts: undefined,
  }
)

const game = createGameStore(props.shortcuts)
provide(GameKey, game)
const { keyDown, keyUp, isRemovedAll, onFullscreenchange } = game

const keyboard = new Keyboard()
if ('keyboard' in navigator) {
  keyboard.setKeyboardLayoutMap(
    (navigator as NavigatorExtend).keyboard as NavigatorKeyboard
  )
  lockKeyboard()
}

const handleKeyDown = (e: KeyboardEvent) => {
  const { altKey, metaKey, shiftKey, ctrlKey } = e
  const key = keyboard.key(e) as string

  keyDown({ altKey, metaKey, shiftKey, ctrlKey, key })
}

const handleKeyUp = (e: KeyboardEvent) => {
  const key = keyboard.key(e) as string

  keyUp(key)
}

useEventListener('fullscreenchange', onFullscreenchange)
useKeyboardEventListener('keydown', handleKeyDown)
useKeyboardEventListener('keyup', handleKeyUp)
</script>

<template>
  <div v-if="!isRemovedAll" class="flex-1 flex flex-col">
    <PieChart />
    <QuestionShow />
    <CorrectAnswer />
    <KeyCombinationForm />
    <div class="my-auto">
      <ShortcutsShow />
      <RestoreButton />
    </div>
    <ToolsAndCategoriesModal />
  </div>
  <div v-else>
    <span>出題できるショートカットキーがありません。</span>
    <RestoreButton
      class="bg-blue-700 hover:bg-blue-500 text-white font-bold py-2 px-4"
    />
  </div>
</template>

// src/views/GameView.tsx
import { useEffect, useMemo, useState } from 'preact/hooks'

import CorrectAnswer from '@/components/CorrectAnswer'
import KeyCombinationForm from '@/components/KeyCombinationForm'
import PieChart from '@/components/PieChart'
import QuestionShow from '@/components/QuestionShow'
import RestoreButton from '@/components/RestoreButton'
import ShortcutsShow from '@/components/ShortcutsShow'
import ToolsAndCategoriesModal from '@/components/ToolsAndCategoriesModal'
import useEventListener from '@/composables/use-event-listener'
import useKeyboardEventListener from '@/composables/use-keyboard-event-listener'
import createGameStore from '@/stores/game'
import GameKey from '@/stores/game-key'
import type {
  NavigatorExtend,
  NavigatorKeyboard,
  Shortcut,
} from '@/types/interfaces'
import Keyboard from '@/utils/keyboard'
import lockKeyboard from '@/utils/lock-keyboard'

type Props = {
  shortcuts?: readonly Shortcut[]
}

export default function GameView({ shortcuts }: Props) {
  const [, forceUpdate] = useState(0)
  const game = useMemo(
    () => createGameStore(shortcuts, () => forceUpdate((value) => value + 1)),
    [shortcuts],
  )

  const keyboard = useMemo(() => new Keyboard(), [])

  useEffect(() => {
    if ('keyboard' in navigator) {
      void keyboard.setKeyboardLayoutMap(
        (navigator as NavigatorExtend).keyboard as NavigatorKeyboard,
      )
      lockKeyboard()
    }
  }, [keyboard])

  const handleKeyDown = (e: KeyboardEvent) => {
    const { altKey, metaKey, shiftKey, ctrlKey } = e
    const key = keyboard.key(e) as string

    game.keyDown({ altKey, metaKey, shiftKey, ctrlKey, key })
  }

  const handleKeyUp = (e: KeyboardEvent) => {
    const key = keyboard.key(e) as string

    game.keyUp(key)
  }

  useEventListener('fullscreenchange', game.onFullscreenchange)
  useKeyboardEventListener('keydown', handleKeyDown)
  useKeyboardEventListener('keyup', handleKeyUp)

  return (
    <GameKey.Provider value={game}>
      {!game.isRemovedAll ? (
        <div class="flex-1 flex flex-col">
          <PieChart />
          <QuestionShow />
          <CorrectAnswer />
          <KeyCombinationForm />
          <div class="my-auto">
            <ShortcutsShow />
            <RestoreButton />
          </div>
          <ToolsAndCategoriesModal />
        </div>
      ) : (
        <div>
          <span>出題できるショートカットキーがありません。</span>
          <RestoreButton class="bg-blue-700 hover:bg-blue-500 text-white font-bold py-2 px-4" />
        </div>
      )}
    </GameKey.Provider>
  )
}
