// src/components/CategoryCard.tsx
import type { ButtonHTMLAttributes } from 'preact'

import IconGlyph from '@/components/IconGlyph'
import PieChartOfMasteredRate from '@/components/PieChartOfMasteredRate'

type Props = ButtonHTMLAttributes<HTMLButtonElement> & {
  name: string
  masteredRate: number
  isSelected: boolean
}

export default function CategoryCard({
  name,
  masteredRate,
  isSelected,
  class: className,
  ...rest
}: Props) {
  return (
    <button
      type="button"
      class={`flex justify-between items-center w-10/12 h-20 bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 transition duration-200 hover:ease-out ${className ?? ''}`}
      {...rest}
    >
      <div class="mx-2 flex space-x-3 text-left">
        <div class="flex h-8 w-8 justify-center self-center">
          {isSelected ? (
            <IconGlyph
              class="text-green-400 inline-block"
              name="check-circle"
            />
          ) : (
            <div class="self-center h-6 w-6 m-1 rounded-full border-2 border-gray-300" />
          )}
        </div>
        <h3 class="my-auto text-xl font-bold tracking-tight">{name}</h3>
      </div>

      <div class="flex h-20">
        <PieChartOfMasteredRate masteredRate={masteredRate} />
      </div>
    </button>
  )
}

// src/components/CategoryCard.vue
<script setup lang="ts">
import IconGlyph from '@/components/IconGlyph.vue'
import PieChartOfMasteredRate from '@/components/PieChartOfMasteredRate.vue'

defineProps<{ name: string; masteredRate: number; isSelected: boolean }>()
</script>

<template>
  <button
    class="flex justify-between items-center w-10/12 h-20 bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 transition duration-200 hover:ease-out"
  >
    <div class="mx-2 flex space-x-3 text-left">
      <div class="flex h-8 w-8 justify-center self-center">
        <IconGlyph
          v-if="isSelected"
          class="text-green-400 inline-block"
          name="check-circle"
        />

        <div
          v-else
          class="self-center h-6 w-6 m-1 rounded-full border-2 border-gray-300"
        />
      </div>
      <h3 class="my-auto text-xl font-bold tracking-tight">
        {{ name }}
      </h3>
    </div>

    <div class="flex h-20">
      <PieChartOfMasteredRate :mastered-rate="masteredRate" />
    </div>
  </button>
</template>
