// src/components/ModalContent.vue
<script setup lang="ts">
defineProps<{ isShow?: boolean; isEnterFromRight?: boolean }>()
</script>

<template>
  <transition
    enter-active-class="duration-200 ease-in"
    :enter-from-class="`transform opacity-0 ${
      isEnterFromRight ? '-translate-x-6' : 'translate-x-6'
    }`"
    enter-to-class="opacity-100"
    leave-active-class="duration-200 ease-out"
    leave-from-class="opacity-0 absolute"
    leave-to-class="opacity-0 absolute"
  >
    <slot v-if="isShow"></slot>
  </transition>
</template>

// src/components/ModalContent.tsx
import type { ComponentChildren } from 'preact'

type Props = {
  isShow?: boolean
  isEnterFromRight?: boolean
  children: ComponentChildren
}

export default function ModalContent({
  isShow = false,
  isEnterFromRight = false,
  children,
}: Props) {
  if (!isShow) {
    return null
  }

  return (
    <div
      class={
        isEnterFromRight
          ? 'duration-200 ease-in transform opacity-0 -translate-x-6'
          : 'duration-200 ease-in transform opacity-0 translate-x-6'
      }
    >
      {children}
    </div>
  )
}
