// src/components/ToolsAndCategoriesModal.tsx
import { useState } from 'preact/hooks'

import CategorySelect from '@/components/CategorySelect'
import Modal from '@/components/Modal'
import ModalContent from '@/components/ModalContent'
import ToolSelect from '@/components/ToolSelect'
import GameKey from '@/stores/game-key'
import ModalKey from '@/stores/modal-key'
import { injectStrict } from '@/utils/inject-strict'

export default function ToolsAndCategoriesModal() {
  const { state, selectToolAndCategories, exitSelectionOfToolAndCategories } =
    injectStrict(GameKey, 'GameKey')
  const { modalState, hideToolsAndCategoriesModal } = injectStrict(
    ModalKey,
    'ModalKey',
  )
  const [tool, setTool] = useState('')

  const select = (categories: string[]) => {
    selectToolAndCategories(tool, categories)
    hideToolsAndCategoriesModal()
  }

  const hide = () => {
    exitSelectionOfToolAndCategories()
    setTool('')
    hideToolsAndCategoriesModal()
  }

  return (
    <Modal
      isShow={
        state.isSelectToolsKeyPressed ||
        modalState.isToolsAndCategoriesModalVisible
      }
      onClose={hide}
    >
      <ModalContent isShow={tool === ''} isEnterFromRight={true}>
        <ToolSelect onSelectTool={setTool} />
      </ModalContent>
      <ModalContent isShow={tool !== ''} isEnterFromRight={false}>
        <CategorySelect
          tool={tool}
          categories={[...state.categories]}
          onSelectToolAndCategories={select}
          onResetTool={() => setTool('')}
        />
      </ModalContent>
    </Modal>
  )
}

// src/components/ToolsAndCategoriesModal.vue
<script setup lang="ts">
import { ref } from 'vue'

import CategorySelect from '@/components/CategorySelect.vue'
import Modal from '@/components/Modal.vue'
import ModalContent from '@/components/ModalContent.vue'
import ToolSelect from '@/components/ToolSelect.vue'
import GameKey from '@/stores/game-key'
import ModalKey from '@/stores/modal-key'
import { injectStrict } from '@/utils/inject-strict'

const { state, selectToolAndCategories } = injectStrict(GameKey)
const { modalState, hideToolsAndCategoriesModal } = injectStrict(ModalKey)

const tool = ref('')

const select = (categories: string[]) => {
  selectToolAndCategories(tool.value, categories)
  hideToolsAndCategoriesModal()
}
</script>

<template>
  <Modal
    ref="modal"
    :is-show="
      state.isSelectToolsKeyPressed ||
      modalState.isToolsAndCategoriesModalVisible
    "
  >
    <ModalContent :is-show="tool === ''" :is-enter-from-right="true">
      <ToolSelect @select-tool="(selectedTool) => (tool = selectedTool)" />
    </ModalContent>
    <ModalContent :is-show="tool !== ''" :is-enter-from-right="false">
      <CategorySelect
        :tool="tool"
        :categories="[...state.categories]"
        @select-tool-and-categories="(categories) => select(categories)"
        @reset-tool="tool = ''"
      />
    </ModalContent>
  </Modal>
</template>
